services:
  app:
    build: .
    ports:
      - "5060:5060"
    volumes:
      - .:/app
      - ./audio:/app/audio
    env_file:
      - .env
    command: python app.py

  opensips:
    image: opensips/opensips:3.3
    ports:
      - "5060:5060/udp"
    volumes:
      - ./cfg:/usr/local/etc/opensips
      - ./audio:/var/www/html/audio
    depends_on:
      - app
      - rtpengine  # Adiciona dependência do rtpengine
    command: opensips -f /usr/local/etc/opensips/opensips.cfg
    networks:
      - internal-network

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./audio:/var/www/html/audio
    depends_on:
      - app
    networks:
      - internal-network

  rtpengine:
    image: opensips/rtpengine:latest # Use a imagem oficial do rtpengine
    ports:
      - "2222:2222/udp"  # Exponha a porta do rtpengine (se necessário)
    volumes:
      - ./rtpengine:/etc/rtpengine # Montar um diretório para arquivos de configuração do rtpengine (opcional)
    # Se você não tiver um arquivo de configuração personalizado, você pode remover a linha 'volumes'
    networks:
      - internal-network
    # Configurações adicionais, como limites de recursos, podem ser adicionadas aqui

# Rede para comunicação interna entre os contêineres
networks:
  internal-network:
    driver: bridge
