services:
  app:
    build: .
    ports:
      - "5060:5060"
    volumes:
      - .:/app
      - ./audio:/app/audio
    env_file:
      - .env
    command: python app.py

  opensips:
    image: opensips/opensips:3.3
    ports:
      - "5060:5060/udp"
    volumes:
      - ./cfg:/usr/local/etc/opensips
      - ./audio:/var/www/html/audio
    depends_on:
      - app
      - rtpengine
    command: opensips -f /usr/local/etc/opensips/opensips.cfg
    networks:
      - internal-network

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./audio:/var/www/html/audio
    depends_on:
      - app
    networks:
      - internal-network

  rtpengine:
    image: sipwise/rtpengine:latest  # Recomendado: imagem oficial
    ports:
      - "2222:2222/udp"
    # volumes:  # Remova esta linha se não usar um arquivo de configuração personalizado
    #   - ./rtpengine:/etc/rtpengine
    depends_on: # Adicionando dependências para o rtpengine
      - app
      - nginx
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
