version: '3.8'

services:
  app:
    build: .
    ports:
      - "5060:5060"
    volumes:
      - .:/app  # Montar a raiz do projeto em /app
      - ./audio:/app/audio
    env_file:
      - .env
    command: python app.py

  opensips:
    image: opensips/opensips:3.3
    ports:
      - "5060:5060/udp"
    volumes:
      - ./cfg:/usr/local/etc/opensips
      - ./audio:/var/www/html/audio
    depends_on:
      - app
    command: opensips -f /usr/local/etc/opensips/opensips.cfg

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./audio:/var/www/html/audio
    depends_on:
      - app
