version: '3.8'

services:
  app:
    build: .
    ports:
      - "5060:5060"
    volumes:
      - .:/app
    env_file:
      - .env  # Carregar variáveis de ambiente do arquivo .env
    command: python app.py
